import React from 'react'
import SideBar from '/components/analytics/src/SideBar'
import TopBar from '/components/analytics/src/TopBar'
import Head from 'next/head'
import Footer from '../src/Footer'
import hm_l from "/styles/light/Home.module.css";
import hm_d from "/styles/Home.module.css";

let hm = hm_l

function RootLayout({children}) {
  return (
    <>
     <Head>
        <title>Direct Private Offers | Receipts and Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/handshake.png" />
    </Head>
    <TopBar mode={hm} />
    {/* <SideBar /> */}
    <main mode={hm}>{children}</main>
    <Footer />
    </>
  )
}

export default RootLayout