import React from 'react'
import SideBar from '/components/analytics/src/SideBar'
import TopBar from '/components/analytics/src/TopBar'
import Head from 'next/head'
import Footer from '../src/Footer'



function RootLayout({children}) {
  return (
    <>
     <Head>
        <title>Direct Private Offers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/handshake.png" />
    </Head>
    <TopBar />
    <SideBar />
    <main>{children}</main>
    <Footer />
    </>
  )
}

export default RootLayout